import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.api.provider.Property

/**
 * A task that automatically synchronizes the project's versioning and naming configuration
 * from Gradle into the iOS `Config.xcconfig` file.
 *
 * This eliminates the need for manual edits in the iOS configuration and ensures that
 * the product name, bundle identifier, marketing version, and build number are always
 * consistent with the rest of the project.
 *
 * Mapping to Xcode:
 * When 'Generate Info.plist File' is enabled in Xcode, these build settings are mapped:
 * - MARKETING_VERSION -> CFBundleShortVersionString (Version Name)
 * - CURRENT_PROJECT_VERSION -> CFBundleVersion (Build Number)
 * - PRODUCT_NAME -> CFBundleName (App Label)
 */
abstract class SyncIosVersionTask : DefaultTask() {

    @get:OutputFile
    abstract val configFile: RegularFileProperty

    @get:Input
    abstract val appName: Property<String>
    @get:Input
    abstract val appLabel: Property<String>
    @get:Input
    abstract val bundleId: Property<String>
    @get:Input
    abstract val appMajor: Property<String>
    @get:Input
    abstract val appStage: Property<String>
    @get:Input
    abstract val numericVersion: Property<String>
    @get:Input
    abstract val buildNumber: Property<String>

    @TaskAction
    fun sync() {
        val file = configFile.get().asFile
        val content = """
            // This file is automatically generated by the 'syncIosVersion' Gradle task.
            // DO NOT EDIT MANUALLY.
            
            TEAM_ID = T9VWZWPAQ5

            PRODUCT_NAME = ${appLabel.get()}
            PRODUCT_BUNDLE_IDENTIFIER = ${bundleId.get()}$(TEAM_ID)

            // Apple's "Build Number" (must be a unique incrementing integer)
            CURRENT_PROJECT_VERSION = ${buildNumber.get()}
            // Apple's "Version Name" (numeric format for compatibility)
            MARKETING_VERSION = ${numericVersion.get()}
            
            // Custom Metadata for About Screen
            ${BuildConstants.KEY_IOS_APP_NAME} = ${appName.get()}
            ${BuildConstants.KEY_IOS_APP_MAJOR} = ${appMajor.get()}
            ${BuildConstants.KEY_IOS_APP_STAGE} = ${appStage.get()}
            
            // Map build settings to Info.plist keys
            INFOPLIST_KEY_AppName = $(${BuildConstants.KEY_IOS_APP_NAME})
            INFOPLIST_KEY_AppMajor = $(${BuildConstants.KEY_IOS_APP_MAJOR})
            INFOPLIST_KEY_AppStage = $(${BuildConstants.KEY_IOS_APP_STAGE})
        """.trimIndent()
        
        file.writeText(content)
        println("Synced iOS version to ${file.absolutePath}")
    }
}
